markdown: rdiscount
pygments: true
permalink: pretty
url: http://benediktmeurer.de
title: Benedikt Meurer
description: Personal website of Benedikt Meurer.
author: Benedikt Meurer
atom: http://feeds.feedburner.com/benediktmeurer

paginate: 5

exclude:
  - Rakefile
  - README.markdown

